apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nitte-prod

resources:
  - ../../base
  - mesh.yaml

# Pin every workload in this environment to the prod worker node,
# and point the Keycloak admin console at the gateway host.
patches:
  - target:
      kind: Deployment
      name: keycloak
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KC_PROXY
          value: "edge"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KC_HOSTNAME_ADMIN_URL
          value: "http://keycloak.prod.nitte.local:8080"
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ignored
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/hostname: workervm2
  - target:
      kind: Job
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ignored
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/hostname: workervm2
  - target:
      kind: DaemonSet
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: ignored
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/hostname: workervm2
