apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: gitops-system
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Enable Helm chart inflation for Kustomize deployments (required for SonarQube)
  kustomize.buildOptions: "--enable-helm"
