apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-podtemplates
rules:
- apiGroups: [""]
  resources: ["podtemplates"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-podtemplates-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: gitops-system
roleRef:
  kind: ClusterRole
  name: argocd-application-controller-podtemplates
  apiGroup: rbac.authorization.k8s.io
